### ISSUE TITLE
Need sudo to install pip ?

### ISSUE THREAD

**Issue by soulmachine** [hayajo/macbook-provision#1]
I tried to `pip install ansible` to install pip on my macbook but failed, the error message is:

```
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 378, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 324, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/usr/local/bin/ansible'
```

Then I used `sudo pip install ansible` and it succeeded.

**Comment by hayajo** [comment]
Hello.

`sudo` should not be necessary if you use the python installed via [Homebrew](http://brew.sh/).

```
9:05:22 [imai.h ~]$ brew list | grep python
python

9:05:46 [imai.h ~]$ ls -l `which python`
lrwxr-xr-x  1 imai.h  admin  34  7 28 11:53 /usr/local/bin/python -> ../Cellar/python/2.7.12/bin/python

9:05:48 [imai.h ~]$ which pip
/usr/local/bin/pip

9:05:53 [imai.h ~]$ pip list | grep ansible
[1]    41526 done       pip list |
       41527 exit 1     grep ansible

9:06:18 [imai.h ~]$ pip install ansible
Collecting ansible
Requirement already satisfied (use --upgrade to upgrade): paramiko in /usr/local/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.6 in /usr/local/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): PyYAML in /usr/local/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): jinja2 in /usr/local/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): ecdsa>=0.11 in /usr/local/lib/python2.7/site-packages (from paramiko->ansible)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /usr/local/lib/python2.7/site-packages (from jinja2->ansible)
Installing collected packages: ansible
Successfully installed ansible-2.1.1.0

9:06:32 [imai.h ~]$ pip list | grep ansible
ansible (2.1.1.0)
```
